# NOTE: dirs ending in / list all projects within
dirs  = [
  "~/code/",
  "~/.config/kitty/meow",
]

# Sources shown by default when switch launches (valid: open, local, remote, set, history)
# default_sources = ["open", "local", "set"]

template = ["nvim", "$SHELL"]

# NOTE: on macos, typically have to define full path to fzf
fzf = "/opt/homebrew/bin/fzf"

github = ["taylorzr", "AquaTeenHungerForce"]

[keybindings]
default = "ctrl-a"
remote = "ctrl-r"
history = "ctrl-i"
open = "ctrl-t"
